apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingassistantservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingassistantservice
  template:
    metadata:
      labels:
        app: shoppingassistantservice
    spec:
      imagePullSecrets:
        - name: ecr-creds
      containers:
        - name: shoppingassistantservice
          image: __IMAGE_NAME__
          ports:
            - containerPort: 8080
